// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgBattleStartArena.proto

package com.felania.msldb;

public final class MsgBattleStartArenaOuterClass {
  private MsgBattleStartArenaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgBattleStartArenaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msggamedata.MsgBattleStartArena)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 list_chunk_id = 1;</code>
     */
    int getListChunkId();

    /**
     * <code>uint64 candidate_user_id = 2;</code>
     */
    long getCandidateUserId();

    /**
     * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
     */
    boolean hasMonsterSlot();
    /**
     * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
     */
    com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData getMonsterSlot();
    /**
     * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
     */
    com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotDataOrBuilder getMonsterSlotOrBuilder();
  }
  /**
   * Protobuf type {@code msggamedata.MsgBattleStartArena}
   */
  public  static final class MsgBattleStartArena extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msggamedata.MsgBattleStartArena)
      MsgBattleStartArenaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgBattleStartArena.newBuilder() to construct.
    private MsgBattleStartArena(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgBattleStartArena() {
      listChunkId_ = 0;
      candidateUserId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgBattleStartArena(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              listChunkId_ = input.readUInt32();
              break;
            }
            case 16: {

              candidateUserId_ = input.readUInt64();
              break;
            }
            case 26: {
              com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.Builder subBuilder = null;
              if (monsterSlot_ != null) {
                subBuilder = monsterSlot_.toBuilder();
              }
              monsterSlot_ = input.readMessage(com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(monsterSlot_);
                monsterSlot_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.felania.msldb.MsgBattleStartArenaOuterClass.internal_static_msggamedata_MsgBattleStartArena_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.felania.msldb.MsgBattleStartArenaOuterClass.internal_static_msggamedata_MsgBattleStartArena_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena.class, com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena.Builder.class);
    }

    public static final int LIST_CHUNK_ID_FIELD_NUMBER = 1;
    private int listChunkId_;
    /**
     * <code>uint32 list_chunk_id = 1;</code>
     */
    public int getListChunkId() {
      return listChunkId_;
    }

    public static final int CANDIDATE_USER_ID_FIELD_NUMBER = 2;
    private long candidateUserId_;
    /**
     * <code>uint64 candidate_user_id = 2;</code>
     */
    public long getCandidateUserId() {
      return candidateUserId_;
    }

    public static final int MONSTER_SLOT_FIELD_NUMBER = 3;
    private com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData monsterSlot_;
    /**
     * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
     */
    public boolean hasMonsterSlot() {
      return monsterSlot_ != null;
    }
    /**
     * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
     */
    public com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData getMonsterSlot() {
      return monsterSlot_ == null ? com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.getDefaultInstance() : monsterSlot_;
    }
    /**
     * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
     */
    public com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotDataOrBuilder getMonsterSlotOrBuilder() {
      return getMonsterSlot();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (listChunkId_ != 0) {
        output.writeUInt32(1, listChunkId_);
      }
      if (candidateUserId_ != 0L) {
        output.writeUInt64(2, candidateUserId_);
      }
      if (monsterSlot_ != null) {
        output.writeMessage(3, getMonsterSlot());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (listChunkId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, listChunkId_);
      }
      if (candidateUserId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, candidateUserId_);
      }
      if (monsterSlot_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMonsterSlot());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena)) {
        return super.equals(obj);
      }
      com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena other = (com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena) obj;

      boolean result = true;
      result = result && (getListChunkId()
          == other.getListChunkId());
      result = result && (getCandidateUserId()
          == other.getCandidateUserId());
      result = result && (hasMonsterSlot() == other.hasMonsterSlot());
      if (hasMonsterSlot()) {
        result = result && getMonsterSlot()
            .equals(other.getMonsterSlot());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LIST_CHUNK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getListChunkId();
      hash = (37 * hash) + CANDIDATE_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCandidateUserId());
      if (hasMonsterSlot()) {
        hash = (37 * hash) + MONSTER_SLOT_FIELD_NUMBER;
        hash = (53 * hash) + getMonsterSlot().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msggamedata.MsgBattleStartArena}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msggamedata.MsgBattleStartArena)
        com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArenaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.felania.msldb.MsgBattleStartArenaOuterClass.internal_static_msggamedata_MsgBattleStartArena_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.felania.msldb.MsgBattleStartArenaOuterClass.internal_static_msggamedata_MsgBattleStartArena_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena.class, com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena.Builder.class);
      }

      // Construct using com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        listChunkId_ = 0;

        candidateUserId_ = 0L;

        if (monsterSlotBuilder_ == null) {
          monsterSlot_ = null;
        } else {
          monsterSlot_ = null;
          monsterSlotBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.felania.msldb.MsgBattleStartArenaOuterClass.internal_static_msggamedata_MsgBattleStartArena_descriptor;
      }

      public com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena getDefaultInstanceForType() {
        return com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena.getDefaultInstance();
      }

      public com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena build() {
        com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena buildPartial() {
        com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena result = new com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena(this);
        result.listChunkId_ = listChunkId_;
        result.candidateUserId_ = candidateUserId_;
        if (monsterSlotBuilder_ == null) {
          result.monsterSlot_ = monsterSlot_;
        } else {
          result.monsterSlot_ = monsterSlotBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena) {
          return mergeFrom((com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena other) {
        if (other == com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena.getDefaultInstance()) return this;
        if (other.getListChunkId() != 0) {
          setListChunkId(other.getListChunkId());
        }
        if (other.getCandidateUserId() != 0L) {
          setCandidateUserId(other.getCandidateUserId());
        }
        if (other.hasMonsterSlot()) {
          mergeMonsterSlot(other.getMonsterSlot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int listChunkId_ ;
      /**
       * <code>uint32 list_chunk_id = 1;</code>
       */
      public int getListChunkId() {
        return listChunkId_;
      }
      /**
       * <code>uint32 list_chunk_id = 1;</code>
       */
      public Builder setListChunkId(int value) {
        
        listChunkId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 list_chunk_id = 1;</code>
       */
      public Builder clearListChunkId() {
        
        listChunkId_ = 0;
        onChanged();
        return this;
      }

      private long candidateUserId_ ;
      /**
       * <code>uint64 candidate_user_id = 2;</code>
       */
      public long getCandidateUserId() {
        return candidateUserId_;
      }
      /**
       * <code>uint64 candidate_user_id = 2;</code>
       */
      public Builder setCandidateUserId(long value) {
        
        candidateUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 candidate_user_id = 2;</code>
       */
      public Builder clearCandidateUserId() {
        
        candidateUserId_ = 0L;
        onChanged();
        return this;
      }

      private com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData monsterSlot_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData, com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.Builder, com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotDataOrBuilder> monsterSlotBuilder_;
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      public boolean hasMonsterSlot() {
        return monsterSlotBuilder_ != null || monsterSlot_ != null;
      }
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      public com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData getMonsterSlot() {
        if (monsterSlotBuilder_ == null) {
          return monsterSlot_ == null ? com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.getDefaultInstance() : monsterSlot_;
        } else {
          return monsterSlotBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      public Builder setMonsterSlot(com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData value) {
        if (monsterSlotBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          monsterSlot_ = value;
          onChanged();
        } else {
          monsterSlotBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      public Builder setMonsterSlot(
          com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.Builder builderForValue) {
        if (monsterSlotBuilder_ == null) {
          monsterSlot_ = builderForValue.build();
          onChanged();
        } else {
          monsterSlotBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      public Builder mergeMonsterSlot(com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData value) {
        if (monsterSlotBuilder_ == null) {
          if (monsterSlot_ != null) {
            monsterSlot_ =
              com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.newBuilder(monsterSlot_).mergeFrom(value).buildPartial();
          } else {
            monsterSlot_ = value;
          }
          onChanged();
        } else {
          monsterSlotBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      public Builder clearMonsterSlot() {
        if (monsterSlotBuilder_ == null) {
          monsterSlot_ = null;
          onChanged();
        } else {
          monsterSlot_ = null;
          monsterSlotBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      public com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.Builder getMonsterSlotBuilder() {
        
        onChanged();
        return getMonsterSlotFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      public com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotDataOrBuilder getMonsterSlotOrBuilder() {
        if (monsterSlotBuilder_ != null) {
          return monsterSlotBuilder_.getMessageOrBuilder();
        } else {
          return monsterSlot_ == null ?
              com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.getDefaultInstance() : monsterSlot_;
        }
      }
      /**
       * <code>.msggamedata.MsgMonsterSlotData monster_slot = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData, com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.Builder, com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotDataOrBuilder> 
          getMonsterSlotFieldBuilder() {
        if (monsterSlotBuilder_ == null) {
          monsterSlotBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData, com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotData.Builder, com.felania.msldb.MsgMonsterSlotDataOuterClass.MsgMonsterSlotDataOrBuilder>(
                  getMonsterSlot(),
                  getParentForChildren(),
                  isClean());
          monsterSlot_ = null;
        }
        return monsterSlotBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msggamedata.MsgBattleStartArena)
    }

    // @@protoc_insertion_point(class_scope:msggamedata.MsgBattleStartArena)
    private static final com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena();
    }

    public static com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgBattleStartArena>
        PARSER = new com.google.protobuf.AbstractParser<MsgBattleStartArena>() {
      public MsgBattleStartArena parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgBattleStartArena(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgBattleStartArena> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgBattleStartArena> getParserForType() {
      return PARSER;
    }

    public com.felania.msldb.MsgBattleStartArenaOuterClass.MsgBattleStartArena getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msggamedata_MsgBattleStartArena_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msggamedata_MsgBattleStartArena_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031MsgBattleStartArena.proto\022\013msggamedata" +
      "\032\030MsgMonsterSlotData.proto\"~\n\023MsgBattleS" +
      "tartArena\022\025\n\rlist_chunk_id\030\001 \001(\r\022\031\n\021cand" +
      "idate_user_id\030\002 \001(\004\0225\n\014monster_slot\030\003 \001(" +
      "\0132\037.msggamedata.MsgMonsterSlotDataB\023\n\021co" +
      "m.felania.msldbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.felania.msldb.MsgMonsterSlotDataOuterClass.getDescriptor(),
        }, assigner);
    internal_static_msggamedata_MsgBattleStartArena_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msggamedata_MsgBattleStartArena_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msggamedata_MsgBattleStartArena_descriptor,
        new java.lang.String[] { "ListChunkId", "CandidateUserId", "MonsterSlot", });
    com.felania.msldb.MsgMonsterSlotDataOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
