// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRuneEffect.proto

package com.felania.msldb;

public final class MsgRuneEffectOuterClass {
  private MsgRuneEffectOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgRuneEffectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msggamedata.MsgRuneEffect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.msggamedata.RuneEffectType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.msggamedata.RuneEffectType type = 1;</code>
     */
    com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType getType();

    /**
     * <code>.msggamedata.MonsterElementType element = 2;</code>
     */
    int getElementValue();
    /**
     * <code>.msggamedata.MonsterElementType element = 2;</code>
     */
    com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType getElement();

    /**
     * <code>float prob = 3;</code>
     */
    float getProb();

    /**
     * <code>float v_float = 4;</code>
     */
    float getVFloat();

    /**
     * <code>uint32 v_int = 5;</code>
     */
    int getVInt();
  }
  /**
   * Protobuf type {@code msggamedata.MsgRuneEffect}
   */
  public  static final class MsgRuneEffect extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msggamedata.MsgRuneEffect)
      MsgRuneEffectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgRuneEffect.newBuilder() to construct.
    private MsgRuneEffect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgRuneEffect() {
      type_ = 0;
      element_ = 0;
      prob_ = 0F;
      vFloat_ = 0F;
      vInt_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgRuneEffect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              element_ = rawValue;
              break;
            }
            case 29: {

              prob_ = input.readFloat();
              break;
            }
            case 37: {

              vFloat_ = input.readFloat();
              break;
            }
            case 40: {

              vInt_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.felania.msldb.MsgRuneEffectOuterClass.internal_static_msggamedata_MsgRuneEffect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.felania.msldb.MsgRuneEffectOuterClass.internal_static_msggamedata_MsgRuneEffect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect.class, com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.msggamedata.RuneEffectType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.msggamedata.RuneEffectType type = 1;</code>
     */
    public com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType getType() {
      com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType result = com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType.valueOf(type_);
      return result == null ? com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType.UNRECOGNIZED : result;
    }

    public static final int ELEMENT_FIELD_NUMBER = 2;
    private int element_;
    /**
     * <code>.msggamedata.MonsterElementType element = 2;</code>
     */
    public int getElementValue() {
      return element_;
    }
    /**
     * <code>.msggamedata.MonsterElementType element = 2;</code>
     */
    public com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType getElement() {
      com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType result = com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType.valueOf(element_);
      return result == null ? com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType.UNRECOGNIZED : result;
    }

    public static final int PROB_FIELD_NUMBER = 3;
    private float prob_;
    /**
     * <code>float prob = 3;</code>
     */
    public float getProb() {
      return prob_;
    }

    public static final int V_FLOAT_FIELD_NUMBER = 4;
    private float vFloat_;
    /**
     * <code>float v_float = 4;</code>
     */
    public float getVFloat() {
      return vFloat_;
    }

    public static final int V_INT_FIELD_NUMBER = 5;
    private int vInt_;
    /**
     * <code>uint32 v_int = 5;</code>
     */
    public int getVInt() {
      return vInt_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType.RET_None.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (element_ != com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType.MonsterElementTypeNULL.getNumber()) {
        output.writeEnum(2, element_);
      }
      if (prob_ != 0F) {
        output.writeFloat(3, prob_);
      }
      if (vFloat_ != 0F) {
        output.writeFloat(4, vFloat_);
      }
      if (vInt_ != 0) {
        output.writeUInt32(5, vInt_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType.RET_None.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (element_ != com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType.MonsterElementTypeNULL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, element_);
      }
      if (prob_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, prob_);
      }
      if (vFloat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, vFloat_);
      }
      if (vInt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, vInt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect)) {
        return super.equals(obj);
      }
      com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect other = (com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && element_ == other.element_;
      result = result && (
          java.lang.Float.floatToIntBits(getProb())
          == java.lang.Float.floatToIntBits(
              other.getProb()));
      result = result && (
          java.lang.Float.floatToIntBits(getVFloat())
          == java.lang.Float.floatToIntBits(
              other.getVFloat()));
      result = result && (getVInt()
          == other.getVInt());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
      hash = (53 * hash) + element_;
      hash = (37 * hash) + PROB_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getProb());
      hash = (37 * hash) + V_FLOAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getVFloat());
      hash = (37 * hash) + V_INT_FIELD_NUMBER;
      hash = (53 * hash) + getVInt();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msggamedata.MsgRuneEffect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msggamedata.MsgRuneEffect)
        com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.felania.msldb.MsgRuneEffectOuterClass.internal_static_msggamedata_MsgRuneEffect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.felania.msldb.MsgRuneEffectOuterClass.internal_static_msggamedata_MsgRuneEffect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect.class, com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect.Builder.class);
      }

      // Construct using com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        element_ = 0;

        prob_ = 0F;

        vFloat_ = 0F;

        vInt_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.felania.msldb.MsgRuneEffectOuterClass.internal_static_msggamedata_MsgRuneEffect_descriptor;
      }

      public com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect getDefaultInstanceForType() {
        return com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect.getDefaultInstance();
      }

      public com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect build() {
        com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect buildPartial() {
        com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect result = new com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect(this);
        result.type_ = type_;
        result.element_ = element_;
        result.prob_ = prob_;
        result.vFloat_ = vFloat_;
        result.vInt_ = vInt_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect) {
          return mergeFrom((com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect other) {
        if (other == com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.element_ != 0) {
          setElementValue(other.getElementValue());
        }
        if (other.getProb() != 0F) {
          setProb(other.getProb());
        }
        if (other.getVFloat() != 0F) {
          setVFloat(other.getVFloat());
        }
        if (other.getVInt() != 0) {
          setVInt(other.getVInt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.msggamedata.RuneEffectType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.msggamedata.RuneEffectType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.msggamedata.RuneEffectType type = 1;</code>
       */
      public com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType getType() {
        com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType result = com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType.valueOf(type_);
        return result == null ? com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType.UNRECOGNIZED : result;
      }
      /**
       * <code>.msggamedata.RuneEffectType type = 1;</code>
       */
      public Builder setType(com.felania.msldb.RuneEffectTypeOuterClass.RuneEffectType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.msggamedata.RuneEffectType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int element_ = 0;
      /**
       * <code>.msggamedata.MonsterElementType element = 2;</code>
       */
      public int getElementValue() {
        return element_;
      }
      /**
       * <code>.msggamedata.MonsterElementType element = 2;</code>
       */
      public Builder setElementValue(int value) {
        element_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.msggamedata.MonsterElementType element = 2;</code>
       */
      public com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType getElement() {
        com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType result = com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType.valueOf(element_);
        return result == null ? com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType.UNRECOGNIZED : result;
      }
      /**
       * <code>.msggamedata.MonsterElementType element = 2;</code>
       */
      public Builder setElement(com.felania.msldb.MonsterElementTypeOuterClass.MonsterElementType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        element_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.msggamedata.MonsterElementType element = 2;</code>
       */
      public Builder clearElement() {
        
        element_ = 0;
        onChanged();
        return this;
      }

      private float prob_ ;
      /**
       * <code>float prob = 3;</code>
       */
      public float getProb() {
        return prob_;
      }
      /**
       * <code>float prob = 3;</code>
       */
      public Builder setProb(float value) {
        
        prob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float prob = 3;</code>
       */
      public Builder clearProb() {
        
        prob_ = 0F;
        onChanged();
        return this;
      }

      private float vFloat_ ;
      /**
       * <code>float v_float = 4;</code>
       */
      public float getVFloat() {
        return vFloat_;
      }
      /**
       * <code>float v_float = 4;</code>
       */
      public Builder setVFloat(float value) {
        
        vFloat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float v_float = 4;</code>
       */
      public Builder clearVFloat() {
        
        vFloat_ = 0F;
        onChanged();
        return this;
      }

      private int vInt_ ;
      /**
       * <code>uint32 v_int = 5;</code>
       */
      public int getVInt() {
        return vInt_;
      }
      /**
       * <code>uint32 v_int = 5;</code>
       */
      public Builder setVInt(int value) {
        
        vInt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 v_int = 5;</code>
       */
      public Builder clearVInt() {
        
        vInt_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msggamedata.MsgRuneEffect)
    }

    // @@protoc_insertion_point(class_scope:msggamedata.MsgRuneEffect)
    private static final com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect();
    }

    public static com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgRuneEffect>
        PARSER = new com.google.protobuf.AbstractParser<MsgRuneEffect>() {
      public MsgRuneEffect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgRuneEffect(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgRuneEffect> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgRuneEffect> getParserForType() {
      return PARSER;
    }

    public com.felania.msldb.MsgRuneEffectOuterClass.MsgRuneEffect getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msggamedata_MsgRuneEffect_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msggamedata_MsgRuneEffect_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023MsgRuneEffect.proto\022\013msggamedata\032\024Rune" +
      "EffectType.proto\032\030MonsterElementType.pro" +
      "to\"\232\001\n\rMsgRuneEffect\022)\n\004type\030\001 \001(\0162\033.msg" +
      "gamedata.RuneEffectType\0220\n\007element\030\002 \001(\016" +
      "2\037.msggamedata.MonsterElementType\022\014\n\004pro" +
      "b\030\003 \001(\002\022\017\n\007v_float\030\004 \001(\002\022\r\n\005v_int\030\005 \001(\rB" +
      "\023\n\021com.felania.msldbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.felania.msldb.RuneEffectTypeOuterClass.getDescriptor(),
          com.felania.msldb.MonsterElementTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_msggamedata_MsgRuneEffect_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msggamedata_MsgRuneEffect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msggamedata_MsgRuneEffect_descriptor,
        new java.lang.String[] { "Type", "Element", "Prob", "VFloat", "VInt", });
    com.felania.msldb.RuneEffectTypeOuterClass.getDescriptor();
    com.felania.msldb.MonsterElementTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
