// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRspBattleEndClan.proto

package com.felania.msldb;

public final class MsgRspBattleEndClanOuterClass {
  private MsgRspBattleEndClanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgRspBattleEndClanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msggamedata.MsgRspBattleEndClan)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.msggamedata.BattleEndResultType result = 1;</code>
     */
    int getResultValue();
    /**
     * <code>.msggamedata.BattleEndResultType result = 1;</code>
     */
    com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType getResult();

    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    boolean hasUser();
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    com.felania.msldb.MsgUserOuterClass.MsgUser getUser();
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder getUserOrBuilder();

    /**
     * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
     */
    boolean hasMyInfo();
    /**
     * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
     */
    com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember getMyInfo();
    /**
     * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
     */
    com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMemberOrBuilder getMyInfoOrBuilder();

    /**
     * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
     */
    boolean hasSeasonHistory();
    /**
     * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
     */
    com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory getSeasonHistory();
    /**
     * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
     */
    com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistoryOrBuilder getSeasonHistoryOrBuilder();

    /**
     * <code>uint64 delta_score = 5;</code>
     */
    long getDeltaScore();

    /**
     * <code>uint64 bonus_score = 6;</code>
     */
    long getBonusScore();

    /**
     * <code>uint64 delta_contribution = 7;</code>
     */
    long getDeltaContribution();

    /**
     * <code>uint32 reward_grade = 8;</code>
     */
    int getRewardGrade();

    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> 
        getRewardsList();
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo getRewards(int index);
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    int getRewardsCount();
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    java.util.List<? extends com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> 
        getRewardsOrBuilderList();
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder getRewardsOrBuilder(
        int index);

    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> 
        getRewardsDeltaList();
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo getRewardsDelta(int index);
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    int getRewardsDeltaCount();
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    java.util.List<? extends com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> 
        getRewardsDeltaOrBuilderList();
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder getRewardsDeltaOrBuilder(
        int index);

    /**
     * <code>bool is_first_battle = 11;</code>
     */
    boolean getIsFirstBattle();
  }
  /**
   * Protobuf type {@code msggamedata.MsgRspBattleEndClan}
   */
  public  static final class MsgRspBattleEndClan extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msggamedata.MsgRspBattleEndClan)
      MsgRspBattleEndClanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgRspBattleEndClan.newBuilder() to construct.
    private MsgRspBattleEndClan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgRspBattleEndClan() {
      result_ = 0;
      deltaScore_ = 0L;
      bonusScore_ = 0L;
      deltaContribution_ = 0L;
      rewardGrade_ = 0;
      rewards_ = java.util.Collections.emptyList();
      rewardsDelta_ = java.util.Collections.emptyList();
      isFirstBattle_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgRspBattleEndClan(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 18: {
              com.felania.msldb.MsgUserOuterClass.MsgUser.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.felania.msldb.MsgUserOuterClass.MsgUser.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.Builder subBuilder = null;
              if (myInfo_ != null) {
                subBuilder = myInfo_.toBuilder();
              }
              myInfo_ = input.readMessage(com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(myInfo_);
                myInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.Builder subBuilder = null;
              if (seasonHistory_ != null) {
                subBuilder = seasonHistory_.toBuilder();
              }
              seasonHistory_ = input.readMessage(com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(seasonHistory_);
                seasonHistory_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {

              deltaScore_ = input.readUInt64();
              break;
            }
            case 48: {

              bonusScore_ = input.readUInt64();
              break;
            }
            case 56: {

              deltaContribution_ = input.readUInt64();
              break;
            }
            case 64: {

              rewardGrade_ = input.readUInt32();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                rewards_ = new java.util.ArrayList<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo>();
                mutable_bitField0_ |= 0x00000100;
              }
              rewards_.add(
                  input.readMessage(com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.parser(), extensionRegistry));
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                rewardsDelta_ = new java.util.ArrayList<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo>();
                mutable_bitField0_ |= 0x00000200;
              }
              rewardsDelta_.add(
                  input.readMessage(com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.parser(), extensionRegistry));
              break;
            }
            case 88: {

              isFirstBattle_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          rewards_ = java.util.Collections.unmodifiableList(rewards_);
        }
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          rewardsDelta_ = java.util.Collections.unmodifiableList(rewardsDelta_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.felania.msldb.MsgRspBattleEndClanOuterClass.internal_static_msggamedata_MsgRspBattleEndClan_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.felania.msldb.MsgRspBattleEndClanOuterClass.internal_static_msggamedata_MsgRspBattleEndClan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan.class, com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan.Builder.class);
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>.msggamedata.BattleEndResultType result = 1;</code>
     */
    public int getResultValue() {
      return result_;
    }
    /**
     * <code>.msggamedata.BattleEndResultType result = 1;</code>
     */
    public com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType getResult() {
      com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType result = com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType.valueOf(result_);
      return result == null ? com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType.UNRECOGNIZED : result;
    }

    public static final int USER_FIELD_NUMBER = 2;
    private com.felania.msldb.MsgUserOuterClass.MsgUser user_;
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    public com.felania.msldb.MsgUserOuterClass.MsgUser getUser() {
      return user_ == null ? com.felania.msldb.MsgUserOuterClass.MsgUser.getDefaultInstance() : user_;
    }
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    public com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int MY_INFO_FIELD_NUMBER = 3;
    private com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember myInfo_;
    /**
     * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
     */
    public boolean hasMyInfo() {
      return myInfo_ != null;
    }
    /**
     * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
     */
    public com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember getMyInfo() {
      return myInfo_ == null ? com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.getDefaultInstance() : myInfo_;
    }
    /**
     * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
     */
    public com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMemberOrBuilder getMyInfoOrBuilder() {
      return getMyInfo();
    }

    public static final int SEASON_HISTORY_FIELD_NUMBER = 4;
    private com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory seasonHistory_;
    /**
     * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
     */
    public boolean hasSeasonHistory() {
      return seasonHistory_ != null;
    }
    /**
     * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
     */
    public com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory getSeasonHistory() {
      return seasonHistory_ == null ? com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.getDefaultInstance() : seasonHistory_;
    }
    /**
     * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
     */
    public com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistoryOrBuilder getSeasonHistoryOrBuilder() {
      return getSeasonHistory();
    }

    public static final int DELTA_SCORE_FIELD_NUMBER = 5;
    private long deltaScore_;
    /**
     * <code>uint64 delta_score = 5;</code>
     */
    public long getDeltaScore() {
      return deltaScore_;
    }

    public static final int BONUS_SCORE_FIELD_NUMBER = 6;
    private long bonusScore_;
    /**
     * <code>uint64 bonus_score = 6;</code>
     */
    public long getBonusScore() {
      return bonusScore_;
    }

    public static final int DELTA_CONTRIBUTION_FIELD_NUMBER = 7;
    private long deltaContribution_;
    /**
     * <code>uint64 delta_contribution = 7;</code>
     */
    public long getDeltaContribution() {
      return deltaContribution_;
    }

    public static final int REWARD_GRADE_FIELD_NUMBER = 8;
    private int rewardGrade_;
    /**
     * <code>uint32 reward_grade = 8;</code>
     */
    public int getRewardGrade() {
      return rewardGrade_;
    }

    public static final int REWARDS_FIELD_NUMBER = 9;
    private java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> rewards_;
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    public java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> getRewardsList() {
      return rewards_;
    }
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    public java.util.List<? extends com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> 
        getRewardsOrBuilderList() {
      return rewards_;
    }
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    public int getRewardsCount() {
      return rewards_.size();
    }
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo getRewards(int index) {
      return rewards_.get(index);
    }
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
     */
    public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder getRewardsOrBuilder(
        int index) {
      return rewards_.get(index);
    }

    public static final int REWARDS_DELTA_FIELD_NUMBER = 10;
    private java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> rewardsDelta_;
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    public java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> getRewardsDeltaList() {
      return rewardsDelta_;
    }
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    public java.util.List<? extends com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> 
        getRewardsDeltaOrBuilderList() {
      return rewardsDelta_;
    }
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    public int getRewardsDeltaCount() {
      return rewardsDelta_.size();
    }
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo getRewardsDelta(int index) {
      return rewardsDelta_.get(index);
    }
    /**
     * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
     */
    public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder getRewardsDeltaOrBuilder(
        int index) {
      return rewardsDelta_.get(index);
    }

    public static final int IS_FIRST_BATTLE_FIELD_NUMBER = 11;
    private boolean isFirstBattle_;
    /**
     * <code>bool is_first_battle = 11;</code>
     */
    public boolean getIsFirstBattle() {
      return isFirstBattle_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType.BERT_None.getNumber()) {
        output.writeEnum(1, result_);
      }
      if (user_ != null) {
        output.writeMessage(2, getUser());
      }
      if (myInfo_ != null) {
        output.writeMessage(3, getMyInfo());
      }
      if (seasonHistory_ != null) {
        output.writeMessage(4, getSeasonHistory());
      }
      if (deltaScore_ != 0L) {
        output.writeUInt64(5, deltaScore_);
      }
      if (bonusScore_ != 0L) {
        output.writeUInt64(6, bonusScore_);
      }
      if (deltaContribution_ != 0L) {
        output.writeUInt64(7, deltaContribution_);
      }
      if (rewardGrade_ != 0) {
        output.writeUInt32(8, rewardGrade_);
      }
      for (int i = 0; i < rewards_.size(); i++) {
        output.writeMessage(9, rewards_.get(i));
      }
      for (int i = 0; i < rewardsDelta_.size(); i++) {
        output.writeMessage(10, rewardsDelta_.get(i));
      }
      if (isFirstBattle_ != false) {
        output.writeBool(11, isFirstBattle_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType.BERT_None.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_);
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUser());
      }
      if (myInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMyInfo());
      }
      if (seasonHistory_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSeasonHistory());
      }
      if (deltaScore_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, deltaScore_);
      }
      if (bonusScore_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, bonusScore_);
      }
      if (deltaContribution_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, deltaContribution_);
      }
      if (rewardGrade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, rewardGrade_);
      }
      for (int i = 0; i < rewards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, rewards_.get(i));
      }
      for (int i = 0; i < rewardsDelta_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, rewardsDelta_.get(i));
      }
      if (isFirstBattle_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, isFirstBattle_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan)) {
        return super.equals(obj);
      }
      com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan other = (com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan) obj;

      boolean result = true;
      result = result && result_ == other.result_;
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasMyInfo() == other.hasMyInfo());
      if (hasMyInfo()) {
        result = result && getMyInfo()
            .equals(other.getMyInfo());
      }
      result = result && (hasSeasonHistory() == other.hasSeasonHistory());
      if (hasSeasonHistory()) {
        result = result && getSeasonHistory()
            .equals(other.getSeasonHistory());
      }
      result = result && (getDeltaScore()
          == other.getDeltaScore());
      result = result && (getBonusScore()
          == other.getBonusScore());
      result = result && (getDeltaContribution()
          == other.getDeltaContribution());
      result = result && (getRewardGrade()
          == other.getRewardGrade());
      result = result && getRewardsList()
          .equals(other.getRewardsList());
      result = result && getRewardsDeltaList()
          .equals(other.getRewardsDeltaList());
      result = result && (getIsFirstBattle()
          == other.getIsFirstBattle());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasMyInfo()) {
        hash = (37 * hash) + MY_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getMyInfo().hashCode();
      }
      if (hasSeasonHistory()) {
        hash = (37 * hash) + SEASON_HISTORY_FIELD_NUMBER;
        hash = (53 * hash) + getSeasonHistory().hashCode();
      }
      hash = (37 * hash) + DELTA_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeltaScore());
      hash = (37 * hash) + BONUS_SCORE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBonusScore());
      hash = (37 * hash) + DELTA_CONTRIBUTION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeltaContribution());
      hash = (37 * hash) + REWARD_GRADE_FIELD_NUMBER;
      hash = (53 * hash) + getRewardGrade();
      if (getRewardsCount() > 0) {
        hash = (37 * hash) + REWARDS_FIELD_NUMBER;
        hash = (53 * hash) + getRewardsList().hashCode();
      }
      if (getRewardsDeltaCount() > 0) {
        hash = (37 * hash) + REWARDS_DELTA_FIELD_NUMBER;
        hash = (53 * hash) + getRewardsDeltaList().hashCode();
      }
      hash = (37 * hash) + IS_FIRST_BATTLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFirstBattle());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msggamedata.MsgRspBattleEndClan}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msggamedata.MsgRspBattleEndClan)
        com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.felania.msldb.MsgRspBattleEndClanOuterClass.internal_static_msggamedata_MsgRspBattleEndClan_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.felania.msldb.MsgRspBattleEndClanOuterClass.internal_static_msggamedata_MsgRspBattleEndClan_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan.class, com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan.Builder.class);
      }

      // Construct using com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRewardsFieldBuilder();
          getRewardsDeltaFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        result_ = 0;

        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        if (myInfoBuilder_ == null) {
          myInfo_ = null;
        } else {
          myInfo_ = null;
          myInfoBuilder_ = null;
        }
        if (seasonHistoryBuilder_ == null) {
          seasonHistory_ = null;
        } else {
          seasonHistory_ = null;
          seasonHistoryBuilder_ = null;
        }
        deltaScore_ = 0L;

        bonusScore_ = 0L;

        deltaContribution_ = 0L;

        rewardGrade_ = 0;

        if (rewardsBuilder_ == null) {
          rewards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          rewardsBuilder_.clear();
        }
        if (rewardsDeltaBuilder_ == null) {
          rewardsDelta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
        } else {
          rewardsDeltaBuilder_.clear();
        }
        isFirstBattle_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.felania.msldb.MsgRspBattleEndClanOuterClass.internal_static_msggamedata_MsgRspBattleEndClan_descriptor;
      }

      public com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan getDefaultInstanceForType() {
        return com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan.getDefaultInstance();
      }

      public com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan build() {
        com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan buildPartial() {
        com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan result = new com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.result_ = result_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (myInfoBuilder_ == null) {
          result.myInfo_ = myInfo_;
        } else {
          result.myInfo_ = myInfoBuilder_.build();
        }
        if (seasonHistoryBuilder_ == null) {
          result.seasonHistory_ = seasonHistory_;
        } else {
          result.seasonHistory_ = seasonHistoryBuilder_.build();
        }
        result.deltaScore_ = deltaScore_;
        result.bonusScore_ = bonusScore_;
        result.deltaContribution_ = deltaContribution_;
        result.rewardGrade_ = rewardGrade_;
        if (rewardsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            rewards_ = java.util.Collections.unmodifiableList(rewards_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.rewards_ = rewards_;
        } else {
          result.rewards_ = rewardsBuilder_.build();
        }
        if (rewardsDeltaBuilder_ == null) {
          if (((bitField0_ & 0x00000200) == 0x00000200)) {
            rewardsDelta_ = java.util.Collections.unmodifiableList(rewardsDelta_);
            bitField0_ = (bitField0_ & ~0x00000200);
          }
          result.rewardsDelta_ = rewardsDelta_;
        } else {
          result.rewardsDelta_ = rewardsDeltaBuilder_.build();
        }
        result.isFirstBattle_ = isFirstBattle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan) {
          return mergeFrom((com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan other) {
        if (other == com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan.getDefaultInstance()) return this;
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasMyInfo()) {
          mergeMyInfo(other.getMyInfo());
        }
        if (other.hasSeasonHistory()) {
          mergeSeasonHistory(other.getSeasonHistory());
        }
        if (other.getDeltaScore() != 0L) {
          setDeltaScore(other.getDeltaScore());
        }
        if (other.getBonusScore() != 0L) {
          setBonusScore(other.getBonusScore());
        }
        if (other.getDeltaContribution() != 0L) {
          setDeltaContribution(other.getDeltaContribution());
        }
        if (other.getRewardGrade() != 0) {
          setRewardGrade(other.getRewardGrade());
        }
        if (rewardsBuilder_ == null) {
          if (!other.rewards_.isEmpty()) {
            if (rewards_.isEmpty()) {
              rewards_ = other.rewards_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensureRewardsIsMutable();
              rewards_.addAll(other.rewards_);
            }
            onChanged();
          }
        } else {
          if (!other.rewards_.isEmpty()) {
            if (rewardsBuilder_.isEmpty()) {
              rewardsBuilder_.dispose();
              rewardsBuilder_ = null;
              rewards_ = other.rewards_;
              bitField0_ = (bitField0_ & ~0x00000100);
              rewardsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRewardsFieldBuilder() : null;
            } else {
              rewardsBuilder_.addAllMessages(other.rewards_);
            }
          }
        }
        if (rewardsDeltaBuilder_ == null) {
          if (!other.rewardsDelta_.isEmpty()) {
            if (rewardsDelta_.isEmpty()) {
              rewardsDelta_ = other.rewardsDelta_;
              bitField0_ = (bitField0_ & ~0x00000200);
            } else {
              ensureRewardsDeltaIsMutable();
              rewardsDelta_.addAll(other.rewardsDelta_);
            }
            onChanged();
          }
        } else {
          if (!other.rewardsDelta_.isEmpty()) {
            if (rewardsDeltaBuilder_.isEmpty()) {
              rewardsDeltaBuilder_.dispose();
              rewardsDeltaBuilder_ = null;
              rewardsDelta_ = other.rewardsDelta_;
              bitField0_ = (bitField0_ & ~0x00000200);
              rewardsDeltaBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRewardsDeltaFieldBuilder() : null;
            } else {
              rewardsDeltaBuilder_.addAllMessages(other.rewardsDelta_);
            }
          }
        }
        if (other.getIsFirstBattle() != false) {
          setIsFirstBattle(other.getIsFirstBattle());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ = 0;
      /**
       * <code>.msggamedata.BattleEndResultType result = 1;</code>
       */
      public int getResultValue() {
        return result_;
      }
      /**
       * <code>.msggamedata.BattleEndResultType result = 1;</code>
       */
      public Builder setResultValue(int value) {
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.msggamedata.BattleEndResultType result = 1;</code>
       */
      public com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType getResult() {
        com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType result = com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType.valueOf(result_);
        return result == null ? com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType.UNRECOGNIZED : result;
      }
      /**
       * <code>.msggamedata.BattleEndResultType result = 1;</code>
       */
      public Builder setResult(com.felania.msldb.BattleEndResultTypeOuterClass.BattleEndResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.msggamedata.BattleEndResultType result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private com.felania.msldb.MsgUserOuterClass.MsgUser user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserOuterClass.MsgUser, com.felania.msldb.MsgUserOuterClass.MsgUser.Builder, com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder> userBuilder_;
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public com.felania.msldb.MsgUserOuterClass.MsgUser getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.felania.msldb.MsgUserOuterClass.MsgUser.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public Builder setUser(com.felania.msldb.MsgUserOuterClass.MsgUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public Builder setUser(
          com.felania.msldb.MsgUserOuterClass.MsgUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public Builder mergeUser(com.felania.msldb.MsgUserOuterClass.MsgUser value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              com.felania.msldb.MsgUserOuterClass.MsgUser.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public com.felania.msldb.MsgUserOuterClass.MsgUser.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.felania.msldb.MsgUserOuterClass.MsgUser.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserOuterClass.MsgUser, com.felania.msldb.MsgUserOuterClass.MsgUser.Builder, com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgUserOuterClass.MsgUser, com.felania.msldb.MsgUserOuterClass.MsgUser.Builder, com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember myInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember, com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.Builder, com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMemberOrBuilder> myInfoBuilder_;
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      public boolean hasMyInfo() {
        return myInfoBuilder_ != null || myInfo_ != null;
      }
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      public com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember getMyInfo() {
        if (myInfoBuilder_ == null) {
          return myInfo_ == null ? com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.getDefaultInstance() : myInfo_;
        } else {
          return myInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      public Builder setMyInfo(com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember value) {
        if (myInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          myInfo_ = value;
          onChanged();
        } else {
          myInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      public Builder setMyInfo(
          com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.Builder builderForValue) {
        if (myInfoBuilder_ == null) {
          myInfo_ = builderForValue.build();
          onChanged();
        } else {
          myInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      public Builder mergeMyInfo(com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember value) {
        if (myInfoBuilder_ == null) {
          if (myInfo_ != null) {
            myInfo_ =
              com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.newBuilder(myInfo_).mergeFrom(value).buildPartial();
          } else {
            myInfo_ = value;
          }
          onChanged();
        } else {
          myInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      public Builder clearMyInfo() {
        if (myInfoBuilder_ == null) {
          myInfo_ = null;
          onChanged();
        } else {
          myInfo_ = null;
          myInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      public com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.Builder getMyInfoBuilder() {
        
        onChanged();
        return getMyInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      public com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMemberOrBuilder getMyInfoOrBuilder() {
        if (myInfoBuilder_ != null) {
          return myInfoBuilder_.getMessageOrBuilder();
        } else {
          return myInfo_ == null ?
              com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.getDefaultInstance() : myInfo_;
        }
      }
      /**
       * <code>.msggamedata.MsgUserClanMember my_info = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember, com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.Builder, com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMemberOrBuilder> 
          getMyInfoFieldBuilder() {
        if (myInfoBuilder_ == null) {
          myInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember, com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMember.Builder, com.felania.msldb.MsgUserClanMemberOuterClass.MsgUserClanMemberOrBuilder>(
                  getMyInfo(),
                  getParentForChildren(),
                  isClean());
          myInfo_ = null;
        }
        return myInfoBuilder_;
      }

      private com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory seasonHistory_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory, com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.Builder, com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistoryOrBuilder> seasonHistoryBuilder_;
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      public boolean hasSeasonHistory() {
        return seasonHistoryBuilder_ != null || seasonHistory_ != null;
      }
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      public com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory getSeasonHistory() {
        if (seasonHistoryBuilder_ == null) {
          return seasonHistory_ == null ? com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.getDefaultInstance() : seasonHistory_;
        } else {
          return seasonHistoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      public Builder setSeasonHistory(com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory value) {
        if (seasonHistoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          seasonHistory_ = value;
          onChanged();
        } else {
          seasonHistoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      public Builder setSeasonHistory(
          com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.Builder builderForValue) {
        if (seasonHistoryBuilder_ == null) {
          seasonHistory_ = builderForValue.build();
          onChanged();
        } else {
          seasonHistoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      public Builder mergeSeasonHistory(com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory value) {
        if (seasonHistoryBuilder_ == null) {
          if (seasonHistory_ != null) {
            seasonHistory_ =
              com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.newBuilder(seasonHistory_).mergeFrom(value).buildPartial();
          } else {
            seasonHistory_ = value;
          }
          onChanged();
        } else {
          seasonHistoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      public Builder clearSeasonHistory() {
        if (seasonHistoryBuilder_ == null) {
          seasonHistory_ = null;
          onChanged();
        } else {
          seasonHistory_ = null;
          seasonHistoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      public com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.Builder getSeasonHistoryBuilder() {
        
        onChanged();
        return getSeasonHistoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      public com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistoryOrBuilder getSeasonHistoryOrBuilder() {
        if (seasonHistoryBuilder_ != null) {
          return seasonHistoryBuilder_.getMessageOrBuilder();
        } else {
          return seasonHistory_ == null ?
              com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.getDefaultInstance() : seasonHistory_;
        }
      }
      /**
       * <code>.msggamedata.MsgClanSeasonHistory season_history = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory, com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.Builder, com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistoryOrBuilder> 
          getSeasonHistoryFieldBuilder() {
        if (seasonHistoryBuilder_ == null) {
          seasonHistoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory, com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistory.Builder, com.felania.msldb.MsgClanSeasonHistoryOuterClass.MsgClanSeasonHistoryOrBuilder>(
                  getSeasonHistory(),
                  getParentForChildren(),
                  isClean());
          seasonHistory_ = null;
        }
        return seasonHistoryBuilder_;
      }

      private long deltaScore_ ;
      /**
       * <code>uint64 delta_score = 5;</code>
       */
      public long getDeltaScore() {
        return deltaScore_;
      }
      /**
       * <code>uint64 delta_score = 5;</code>
       */
      public Builder setDeltaScore(long value) {
        
        deltaScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 delta_score = 5;</code>
       */
      public Builder clearDeltaScore() {
        
        deltaScore_ = 0L;
        onChanged();
        return this;
      }

      private long bonusScore_ ;
      /**
       * <code>uint64 bonus_score = 6;</code>
       */
      public long getBonusScore() {
        return bonusScore_;
      }
      /**
       * <code>uint64 bonus_score = 6;</code>
       */
      public Builder setBonusScore(long value) {
        
        bonusScore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 bonus_score = 6;</code>
       */
      public Builder clearBonusScore() {
        
        bonusScore_ = 0L;
        onChanged();
        return this;
      }

      private long deltaContribution_ ;
      /**
       * <code>uint64 delta_contribution = 7;</code>
       */
      public long getDeltaContribution() {
        return deltaContribution_;
      }
      /**
       * <code>uint64 delta_contribution = 7;</code>
       */
      public Builder setDeltaContribution(long value) {
        
        deltaContribution_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 delta_contribution = 7;</code>
       */
      public Builder clearDeltaContribution() {
        
        deltaContribution_ = 0L;
        onChanged();
        return this;
      }

      private int rewardGrade_ ;
      /**
       * <code>uint32 reward_grade = 8;</code>
       */
      public int getRewardGrade() {
        return rewardGrade_;
      }
      /**
       * <code>uint32 reward_grade = 8;</code>
       */
      public Builder setRewardGrade(int value) {
        
        rewardGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 reward_grade = 8;</code>
       */
      public Builder clearRewardGrade() {
        
        rewardGrade_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> rewards_ =
        java.util.Collections.emptyList();
      private void ensureRewardsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          rewards_ = new java.util.ArrayList<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo>(rewards_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> rewardsBuilder_;

      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> getRewardsList() {
        if (rewardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rewards_);
        } else {
          return rewardsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public int getRewardsCount() {
        if (rewardsBuilder_ == null) {
          return rewards_.size();
        } else {
          return rewardsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo getRewards(int index) {
        if (rewardsBuilder_ == null) {
          return rewards_.get(index);
        } else {
          return rewardsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder setRewards(
          int index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.set(index, value);
          onChanged();
        } else {
          rewardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder setRewards(
          int index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.set(index, builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder addRewards(com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.add(value);
          onChanged();
        } else {
          rewardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder addRewards(
          int index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.add(index, value);
          onChanged();
        } else {
          rewardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder addRewards(
          com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.add(builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder addRewards(
          int index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.add(index, builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder addAllRewards(
          java.lang.Iterable<? extends com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> values) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rewards_);
          onChanged();
        } else {
          rewardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder clearRewards() {
        if (rewardsBuilder_ == null) {
          rewards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          rewardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public Builder removeRewards(int index) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.remove(index);
          onChanged();
        } else {
          rewardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder getRewardsBuilder(
          int index) {
        return getRewardsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder getRewardsOrBuilder(
          int index) {
        if (rewardsBuilder_ == null) {
          return rewards_.get(index);  } else {
          return rewardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public java.util.List<? extends com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> 
           getRewardsOrBuilderList() {
        if (rewardsBuilder_ != null) {
          return rewardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rewards_);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder addRewardsBuilder() {
        return getRewardsFieldBuilder().addBuilder(
            com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder addRewardsBuilder(
          int index) {
        return getRewardsFieldBuilder().addBuilder(
            index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards = 9;</code>
       */
      public java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder> 
           getRewardsBuilderList() {
        return getRewardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> 
          getRewardsFieldBuilder() {
        if (rewardsBuilder_ == null) {
          rewardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder>(
                  rewards_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          rewards_ = null;
        }
        return rewardsBuilder_;
      }

      private java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> rewardsDelta_ =
        java.util.Collections.emptyList();
      private void ensureRewardsDeltaIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          rewardsDelta_ = new java.util.ArrayList<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo>(rewardsDelta_);
          bitField0_ |= 0x00000200;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> rewardsDeltaBuilder_;

      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> getRewardsDeltaList() {
        if (rewardsDeltaBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rewardsDelta_);
        } else {
          return rewardsDeltaBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public int getRewardsDeltaCount() {
        if (rewardsDeltaBuilder_ == null) {
          return rewardsDelta_.size();
        } else {
          return rewardsDeltaBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo getRewardsDelta(int index) {
        if (rewardsDeltaBuilder_ == null) {
          return rewardsDelta_.get(index);
        } else {
          return rewardsDeltaBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder setRewardsDelta(
          int index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo value) {
        if (rewardsDeltaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsDeltaIsMutable();
          rewardsDelta_.set(index, value);
          onChanged();
        } else {
          rewardsDeltaBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder setRewardsDelta(
          int index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder builderForValue) {
        if (rewardsDeltaBuilder_ == null) {
          ensureRewardsDeltaIsMutable();
          rewardsDelta_.set(index, builderForValue.build());
          onChanged();
        } else {
          rewardsDeltaBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder addRewardsDelta(com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo value) {
        if (rewardsDeltaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsDeltaIsMutable();
          rewardsDelta_.add(value);
          onChanged();
        } else {
          rewardsDeltaBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder addRewardsDelta(
          int index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo value) {
        if (rewardsDeltaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsDeltaIsMutable();
          rewardsDelta_.add(index, value);
          onChanged();
        } else {
          rewardsDeltaBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder addRewardsDelta(
          com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder builderForValue) {
        if (rewardsDeltaBuilder_ == null) {
          ensureRewardsDeltaIsMutable();
          rewardsDelta_.add(builderForValue.build());
          onChanged();
        } else {
          rewardsDeltaBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder addRewardsDelta(
          int index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder builderForValue) {
        if (rewardsDeltaBuilder_ == null) {
          ensureRewardsDeltaIsMutable();
          rewardsDelta_.add(index, builderForValue.build());
          onChanged();
        } else {
          rewardsDeltaBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder addAllRewardsDelta(
          java.lang.Iterable<? extends com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo> values) {
        if (rewardsDeltaBuilder_ == null) {
          ensureRewardsDeltaIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rewardsDelta_);
          onChanged();
        } else {
          rewardsDeltaBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder clearRewardsDelta() {
        if (rewardsDeltaBuilder_ == null) {
          rewardsDelta_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000200);
          onChanged();
        } else {
          rewardsDeltaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public Builder removeRewardsDelta(int index) {
        if (rewardsDeltaBuilder_ == null) {
          ensureRewardsDeltaIsMutable();
          rewardsDelta_.remove(index);
          onChanged();
        } else {
          rewardsDeltaBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder getRewardsDeltaBuilder(
          int index) {
        return getRewardsDeltaFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder getRewardsDeltaOrBuilder(
          int index) {
        if (rewardsDeltaBuilder_ == null) {
          return rewardsDelta_.get(index);  } else {
          return rewardsDeltaBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public java.util.List<? extends com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> 
           getRewardsDeltaOrBuilderList() {
        if (rewardsDeltaBuilder_ != null) {
          return rewardsDeltaBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rewardsDelta_);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder addRewardsDeltaBuilder() {
        return getRewardsDeltaFieldBuilder().addBuilder(
            com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder addRewardsDeltaBuilder(
          int index) {
        return getRewardsDeltaFieldBuilder().addBuilder(
            index, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .msggamedata.MsgBattleRewardInfo rewards_delta = 10;</code>
       */
      public java.util.List<com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder> 
           getRewardsDeltaBuilderList() {
        return getRewardsDeltaFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder> 
          getRewardsDeltaFieldBuilder() {
        if (rewardsDeltaBuilder_ == null) {
          rewardsDeltaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfo.Builder, com.felania.msldb.MsgBattleRewardInfoOuterClass.MsgBattleRewardInfoOrBuilder>(
                  rewardsDelta_,
                  ((bitField0_ & 0x00000200) == 0x00000200),
                  getParentForChildren(),
                  isClean());
          rewardsDelta_ = null;
        }
        return rewardsDeltaBuilder_;
      }

      private boolean isFirstBattle_ ;
      /**
       * <code>bool is_first_battle = 11;</code>
       */
      public boolean getIsFirstBattle() {
        return isFirstBattle_;
      }
      /**
       * <code>bool is_first_battle = 11;</code>
       */
      public Builder setIsFirstBattle(boolean value) {
        
        isFirstBattle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_first_battle = 11;</code>
       */
      public Builder clearIsFirstBattle() {
        
        isFirstBattle_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msggamedata.MsgRspBattleEndClan)
    }

    // @@protoc_insertion_point(class_scope:msggamedata.MsgRspBattleEndClan)
    private static final com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan();
    }

    public static com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgRspBattleEndClan>
        PARSER = new com.google.protobuf.AbstractParser<MsgRspBattleEndClan>() {
      public MsgRspBattleEndClan parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgRspBattleEndClan(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgRspBattleEndClan> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgRspBattleEndClan> getParserForType() {
      return PARSER;
    }

    public com.felania.msldb.MsgRspBattleEndClanOuterClass.MsgRspBattleEndClan getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msggamedata_MsgRspBattleEndClan_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msggamedata_MsgRspBattleEndClan_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031MsgRspBattleEndClan.proto\022\013msggamedata" +
      "\032\031BattleEndResultType.proto\032\rMsgUser.pro" +
      "to\032\027MsgUserClanMember.proto\032\032MsgClanSeas" +
      "onHistory.proto\032\031MsgBattleRewardInfo.pro" +
      "to\"\270\003\n\023MsgRspBattleEndClan\0220\n\006result\030\001 \001" +
      "(\0162 .msggamedata.BattleEndResultType\022\"\n\004" +
      "user\030\002 \001(\0132\024.msggamedata.MsgUser\022/\n\007my_i" +
      "nfo\030\003 \001(\0132\036.msggamedata.MsgUserClanMembe" +
      "r\0229\n\016season_history\030\004 \001(\0132!.msggamedata." +
      "MsgClanSeasonHistory\022\023\n\013delta_score\030\005 \001(",
      "\004\022\023\n\013bonus_score\030\006 \001(\004\022\032\n\022delta_contribu" +
      "tion\030\007 \001(\004\022\024\n\014reward_grade\030\010 \001(\r\0221\n\007rewa" +
      "rds\030\t \003(\0132 .msggamedata.MsgBattleRewardI" +
      "nfo\0227\n\rrewards_delta\030\n \003(\0132 .msggamedata" +
      ".MsgBattleRewardInfo\022\027\n\017is_first_battle\030" +
      "\013 \001(\010B\023\n\021com.felania.msldbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.felania.msldb.BattleEndResultTypeOuterClass.getDescriptor(),
          com.felania.msldb.MsgUserOuterClass.getDescriptor(),
          com.felania.msldb.MsgUserClanMemberOuterClass.getDescriptor(),
          com.felania.msldb.MsgClanSeasonHistoryOuterClass.getDescriptor(),
          com.felania.msldb.MsgBattleRewardInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_msggamedata_MsgRspBattleEndClan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msggamedata_MsgRspBattleEndClan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msggamedata_MsgRspBattleEndClan_descriptor,
        new java.lang.String[] { "Result", "User", "MyInfo", "SeasonHistory", "DeltaScore", "BonusScore", "DeltaContribution", "RewardGrade", "Rewards", "RewardsDelta", "IsFirstBattle", });
    com.felania.msldb.BattleEndResultTypeOuterClass.getDescriptor();
    com.felania.msldb.MsgUserOuterClass.getDescriptor();
    com.felania.msldb.MsgUserClanMemberOuterClass.getDescriptor();
    com.felania.msldb.MsgClanSeasonHistoryOuterClass.getDescriptor();
    com.felania.msldb.MsgBattleRewardInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
