// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgRspBattleEndDungeon.proto

package com.felania.msldb;

public final class MsgRspBattleEndDungeonOuterClass {
  private MsgRspBattleEndDungeonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgRspBattleEndDungeonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msggamedata.MsgRspBattleEndDungeon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     */
    boolean hasInfo();
    /**
     * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     */
    com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo getInfo();
    /**
     * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     */
    com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfoOrBuilder getInfoOrBuilder();

    /**
     * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     */
    boolean hasStageHistory();
    /**
     * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     */
    com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory getStageHistory();
    /**
     * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     */
    com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistoryOrBuilder getStageHistoryOrBuilder();

    /**
     * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     */
    boolean hasColossusStageHistory();
    /**
     * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     */
    com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory getColossusStageHistory();
    /**
     * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     */
    com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistoryOrBuilder getColossusStageHistoryOrBuilder();

    /**
     * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     */
    boolean hasClearHistory();
    /**
     * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     */
    com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory getClearHistory();
    /**
     * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     */
    com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistoryOrBuilder getClearHistoryOrBuilder();

    /**
     * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     */
    boolean hasColossusClearReward();
    /**
     * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     */
    com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook getColossusClearReward();
    /**
     * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     */
    com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBookOrBuilder getColossusClearRewardOrBuilder();
  }
  /**
   * Protobuf type {@code msggamedata.MsgRspBattleEndDungeon}
   */
  public  static final class MsgRspBattleEndDungeon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msggamedata.MsgRspBattleEndDungeon)
      MsgRspBattleEndDungeonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgRspBattleEndDungeon.newBuilder() to construct.
    private MsgRspBattleEndDungeon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgRspBattleEndDungeon() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgRspBattleEndDungeon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.Builder subBuilder = null;
              if (info_ != null) {
                subBuilder = info_.toBuilder();
              }
              info_ = input.readMessage(com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(info_);
                info_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.Builder subBuilder = null;
              if (stageHistory_ != null) {
                subBuilder = stageHistory_.toBuilder();
              }
              stageHistory_ = input.readMessage(com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stageHistory_);
                stageHistory_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.Builder subBuilder = null;
              if (colossusStageHistory_ != null) {
                subBuilder = colossusStageHistory_.toBuilder();
              }
              colossusStageHistory_ = input.readMessage(com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(colossusStageHistory_);
                colossusStageHistory_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.Builder subBuilder = null;
              if (clearHistory_ != null) {
                subBuilder = clearHistory_.toBuilder();
              }
              clearHistory_ = input.readMessage(com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(clearHistory_);
                clearHistory_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.Builder subBuilder = null;
              if (colossusClearReward_ != null) {
                subBuilder = colossusClearReward_.toBuilder();
              }
              colossusClearReward_ = input.readMessage(com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(colossusClearReward_);
                colossusClearReward_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.felania.msldb.MsgRspBattleEndDungeonOuterClass.internal_static_msggamedata_MsgRspBattleEndDungeon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.felania.msldb.MsgRspBattleEndDungeonOuterClass.internal_static_msggamedata_MsgRspBattleEndDungeon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon.class, com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon.Builder.class);
    }

    public static final int INFO_FIELD_NUMBER = 1;
    private com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo info_;
    /**
     * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     */
    public boolean hasInfo() {
      return info_ != null;
    }
    /**
     * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     */
    public com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo getInfo() {
      return info_ == null ? com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.getDefaultInstance() : info_;
    }
    /**
     * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
     */
    public com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfoOrBuilder getInfoOrBuilder() {
      return getInfo();
    }

    public static final int STAGE_HISTORY_FIELD_NUMBER = 2;
    private com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory stageHistory_;
    /**
     * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     */
    public boolean hasStageHistory() {
      return stageHistory_ != null;
    }
    /**
     * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     */
    public com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory getStageHistory() {
      return stageHistory_ == null ? com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.getDefaultInstance() : stageHistory_;
    }
    /**
     * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
     */
    public com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistoryOrBuilder getStageHistoryOrBuilder() {
      return getStageHistory();
    }

    public static final int COLOSSUS_STAGE_HISTORY_FIELD_NUMBER = 3;
    private com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory colossusStageHistory_;
    /**
     * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     */
    public boolean hasColossusStageHistory() {
      return colossusStageHistory_ != null;
    }
    /**
     * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     */
    public com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory getColossusStageHistory() {
      return colossusStageHistory_ == null ? com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.getDefaultInstance() : colossusStageHistory_;
    }
    /**
     * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
     */
    public com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistoryOrBuilder getColossusStageHistoryOrBuilder() {
      return getColossusStageHistory();
    }

    public static final int CLEAR_HISTORY_FIELD_NUMBER = 4;
    private com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory clearHistory_;
    /**
     * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     */
    public boolean hasClearHistory() {
      return clearHistory_ != null;
    }
    /**
     * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     */
    public com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory getClearHistory() {
      return clearHistory_ == null ? com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.getDefaultInstance() : clearHistory_;
    }
    /**
     * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
     */
    public com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistoryOrBuilder getClearHistoryOrBuilder() {
      return getClearHistory();
    }

    public static final int COLOSSUS_CLEAR_REWARD_FIELD_NUMBER = 5;
    private com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook colossusClearReward_;
    /**
     * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     */
    public boolean hasColossusClearReward() {
      return colossusClearReward_ != null;
    }
    /**
     * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     */
    public com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook getColossusClearReward() {
      return colossusClearReward_ == null ? com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.getDefaultInstance() : colossusClearReward_;
    }
    /**
     * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
     */
    public com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBookOrBuilder getColossusClearRewardOrBuilder() {
      return getColossusClearReward();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (info_ != null) {
        output.writeMessage(1, getInfo());
      }
      if (stageHistory_ != null) {
        output.writeMessage(2, getStageHistory());
      }
      if (colossusStageHistory_ != null) {
        output.writeMessage(3, getColossusStageHistory());
      }
      if (clearHistory_ != null) {
        output.writeMessage(4, getClearHistory());
      }
      if (colossusClearReward_ != null) {
        output.writeMessage(5, getColossusClearReward());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (info_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getInfo());
      }
      if (stageHistory_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStageHistory());
      }
      if (colossusStageHistory_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getColossusStageHistory());
      }
      if (clearHistory_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getClearHistory());
      }
      if (colossusClearReward_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getColossusClearReward());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon)) {
        return super.equals(obj);
      }
      com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon other = (com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon) obj;

      boolean result = true;
      result = result && (hasInfo() == other.hasInfo());
      if (hasInfo()) {
        result = result && getInfo()
            .equals(other.getInfo());
      }
      result = result && (hasStageHistory() == other.hasStageHistory());
      if (hasStageHistory()) {
        result = result && getStageHistory()
            .equals(other.getStageHistory());
      }
      result = result && (hasColossusStageHistory() == other.hasColossusStageHistory());
      if (hasColossusStageHistory()) {
        result = result && getColossusStageHistory()
            .equals(other.getColossusStageHistory());
      }
      result = result && (hasClearHistory() == other.hasClearHistory());
      if (hasClearHistory()) {
        result = result && getClearHistory()
            .equals(other.getClearHistory());
      }
      result = result && (hasColossusClearReward() == other.hasColossusClearReward());
      if (hasColossusClearReward()) {
        result = result && getColossusClearReward()
            .equals(other.getColossusClearReward());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInfo()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
      }
      if (hasStageHistory()) {
        hash = (37 * hash) + STAGE_HISTORY_FIELD_NUMBER;
        hash = (53 * hash) + getStageHistory().hashCode();
      }
      if (hasColossusStageHistory()) {
        hash = (37 * hash) + COLOSSUS_STAGE_HISTORY_FIELD_NUMBER;
        hash = (53 * hash) + getColossusStageHistory().hashCode();
      }
      if (hasClearHistory()) {
        hash = (37 * hash) + CLEAR_HISTORY_FIELD_NUMBER;
        hash = (53 * hash) + getClearHistory().hashCode();
      }
      if (hasColossusClearReward()) {
        hash = (37 * hash) + COLOSSUS_CLEAR_REWARD_FIELD_NUMBER;
        hash = (53 * hash) + getColossusClearReward().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msggamedata.MsgRspBattleEndDungeon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msggamedata.MsgRspBattleEndDungeon)
        com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.felania.msldb.MsgRspBattleEndDungeonOuterClass.internal_static_msggamedata_MsgRspBattleEndDungeon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.felania.msldb.MsgRspBattleEndDungeonOuterClass.internal_static_msggamedata_MsgRspBattleEndDungeon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon.class, com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon.Builder.class);
      }

      // Construct using com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (infoBuilder_ == null) {
          info_ = null;
        } else {
          info_ = null;
          infoBuilder_ = null;
        }
        if (stageHistoryBuilder_ == null) {
          stageHistory_ = null;
        } else {
          stageHistory_ = null;
          stageHistoryBuilder_ = null;
        }
        if (colossusStageHistoryBuilder_ == null) {
          colossusStageHistory_ = null;
        } else {
          colossusStageHistory_ = null;
          colossusStageHistoryBuilder_ = null;
        }
        if (clearHistoryBuilder_ == null) {
          clearHistory_ = null;
        } else {
          clearHistory_ = null;
          clearHistoryBuilder_ = null;
        }
        if (colossusClearRewardBuilder_ == null) {
          colossusClearReward_ = null;
        } else {
          colossusClearReward_ = null;
          colossusClearRewardBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.felania.msldb.MsgRspBattleEndDungeonOuterClass.internal_static_msggamedata_MsgRspBattleEndDungeon_descriptor;
      }

      public com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon getDefaultInstanceForType() {
        return com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon.getDefaultInstance();
      }

      public com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon build() {
        com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon buildPartial() {
        com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon result = new com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon(this);
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        if (stageHistoryBuilder_ == null) {
          result.stageHistory_ = stageHistory_;
        } else {
          result.stageHistory_ = stageHistoryBuilder_.build();
        }
        if (colossusStageHistoryBuilder_ == null) {
          result.colossusStageHistory_ = colossusStageHistory_;
        } else {
          result.colossusStageHistory_ = colossusStageHistoryBuilder_.build();
        }
        if (clearHistoryBuilder_ == null) {
          result.clearHistory_ = clearHistory_;
        } else {
          result.clearHistory_ = clearHistoryBuilder_.build();
        }
        if (colossusClearRewardBuilder_ == null) {
          result.colossusClearReward_ = colossusClearReward_;
        } else {
          result.colossusClearReward_ = colossusClearRewardBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon) {
          return mergeFrom((com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon other) {
        if (other == com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon.getDefaultInstance()) return this;
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        if (other.hasStageHistory()) {
          mergeStageHistory(other.getStageHistory());
        }
        if (other.hasColossusStageHistory()) {
          mergeColossusStageHistory(other.getColossusStageHistory());
        }
        if (other.hasClearHistory()) {
          mergeClearHistory(other.getClearHistory());
        }
        if (other.hasColossusClearReward()) {
          mergeColossusClearReward(other.getColossusClearReward());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo info_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo, com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.Builder, com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfoOrBuilder> infoBuilder_;
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      public boolean hasInfo() {
        return infoBuilder_ != null || info_ != null;
      }
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      public com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo getInfo() {
        if (infoBuilder_ == null) {
          return info_ == null ? com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.getDefaultInstance() : info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      public Builder setInfo(com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      public Builder setInfo(
          com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      public Builder mergeInfo(com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo value) {
        if (infoBuilder_ == null) {
          if (info_ != null) {
            info_ =
              com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = null;
          onChanged();
        } else {
          info_ = null;
          infoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      public com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.Builder getInfoBuilder() {
        
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      public com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfoOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_ == null ?
              com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.getDefaultInstance() : info_;
        }
      }
      /**
       * <code>.msggamedata.MsgBattleEndBasicInfo info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo, com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.Builder, com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfoOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo, com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfo.Builder, com.felania.msldb.MsgBattleEndBasicInfoOuterClass.MsgBattleEndBasicInfoOrBuilder>(
                  getInfo(),
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }

      private com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory stageHistory_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory, com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.Builder, com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistoryOrBuilder> stageHistoryBuilder_;
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      public boolean hasStageHistory() {
        return stageHistoryBuilder_ != null || stageHistory_ != null;
      }
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      public com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory getStageHistory() {
        if (stageHistoryBuilder_ == null) {
          return stageHistory_ == null ? com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.getDefaultInstance() : stageHistory_;
        } else {
          return stageHistoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      public Builder setStageHistory(com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory value) {
        if (stageHistoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stageHistory_ = value;
          onChanged();
        } else {
          stageHistoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      public Builder setStageHistory(
          com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.Builder builderForValue) {
        if (stageHistoryBuilder_ == null) {
          stageHistory_ = builderForValue.build();
          onChanged();
        } else {
          stageHistoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      public Builder mergeStageHistory(com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory value) {
        if (stageHistoryBuilder_ == null) {
          if (stageHistory_ != null) {
            stageHistory_ =
              com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.newBuilder(stageHistory_).mergeFrom(value).buildPartial();
          } else {
            stageHistory_ = value;
          }
          onChanged();
        } else {
          stageHistoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      public Builder clearStageHistory() {
        if (stageHistoryBuilder_ == null) {
          stageHistory_ = null;
          onChanged();
        } else {
          stageHistory_ = null;
          stageHistoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      public com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.Builder getStageHistoryBuilder() {
        
        onChanged();
        return getStageHistoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      public com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistoryOrBuilder getStageHistoryOrBuilder() {
        if (stageHistoryBuilder_ != null) {
          return stageHistoryBuilder_.getMessageOrBuilder();
        } else {
          return stageHistory_ == null ?
              com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.getDefaultInstance() : stageHistory_;
        }
      }
      /**
       * <code>.msggamedata.MsgUserDungeonStageHistory stage_history = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory, com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.Builder, com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistoryOrBuilder> 
          getStageHistoryFieldBuilder() {
        if (stageHistoryBuilder_ == null) {
          stageHistoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory, com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistory.Builder, com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.MsgUserDungeonStageHistoryOrBuilder>(
                  getStageHistory(),
                  getParentForChildren(),
                  isClean());
          stageHistory_ = null;
        }
        return stageHistoryBuilder_;
      }

      private com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory colossusStageHistory_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory, com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.Builder, com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistoryOrBuilder> colossusStageHistoryBuilder_;
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      public boolean hasColossusStageHistory() {
        return colossusStageHistoryBuilder_ != null || colossusStageHistory_ != null;
      }
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      public com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory getColossusStageHistory() {
        if (colossusStageHistoryBuilder_ == null) {
          return colossusStageHistory_ == null ? com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.getDefaultInstance() : colossusStageHistory_;
        } else {
          return colossusStageHistoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      public Builder setColossusStageHistory(com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory value) {
        if (colossusStageHistoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          colossusStageHistory_ = value;
          onChanged();
        } else {
          colossusStageHistoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      public Builder setColossusStageHistory(
          com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.Builder builderForValue) {
        if (colossusStageHistoryBuilder_ == null) {
          colossusStageHistory_ = builderForValue.build();
          onChanged();
        } else {
          colossusStageHistoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      public Builder mergeColossusStageHistory(com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory value) {
        if (colossusStageHistoryBuilder_ == null) {
          if (colossusStageHistory_ != null) {
            colossusStageHistory_ =
              com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.newBuilder(colossusStageHistory_).mergeFrom(value).buildPartial();
          } else {
            colossusStageHistory_ = value;
          }
          onChanged();
        } else {
          colossusStageHistoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      public Builder clearColossusStageHistory() {
        if (colossusStageHistoryBuilder_ == null) {
          colossusStageHistory_ = null;
          onChanged();
        } else {
          colossusStageHistory_ = null;
          colossusStageHistoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      public com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.Builder getColossusStageHistoryBuilder() {
        
        onChanged();
        return getColossusStageHistoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      public com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistoryOrBuilder getColossusStageHistoryOrBuilder() {
        if (colossusStageHistoryBuilder_ != null) {
          return colossusStageHistoryBuilder_.getMessageOrBuilder();
        } else {
          return colossusStageHistory_ == null ?
              com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.getDefaultInstance() : colossusStageHistory_;
        }
      }
      /**
       * <code>.msggamedata.MsgUserColossusDungeonStageHistory colossus_stage_history = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory, com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.Builder, com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistoryOrBuilder> 
          getColossusStageHistoryFieldBuilder() {
        if (colossusStageHistoryBuilder_ == null) {
          colossusStageHistoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory, com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistory.Builder, com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.MsgUserColossusDungeonStageHistoryOrBuilder>(
                  getColossusStageHistory(),
                  getParentForChildren(),
                  isClean());
          colossusStageHistory_ = null;
        }
        return colossusStageHistoryBuilder_;
      }

      private com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory clearHistory_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory, com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.Builder, com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistoryOrBuilder> clearHistoryBuilder_;
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      public boolean hasClearHistory() {
        return clearHistoryBuilder_ != null || clearHistory_ != null;
      }
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      public com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory getClearHistory() {
        if (clearHistoryBuilder_ == null) {
          return clearHistory_ == null ? com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.getDefaultInstance() : clearHistory_;
        } else {
          return clearHistoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      public Builder setClearHistory(com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory value) {
        if (clearHistoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clearHistory_ = value;
          onChanged();
        } else {
          clearHistoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      public Builder setClearHistory(
          com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.Builder builderForValue) {
        if (clearHistoryBuilder_ == null) {
          clearHistory_ = builderForValue.build();
          onChanged();
        } else {
          clearHistoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      public Builder mergeClearHistory(com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory value) {
        if (clearHistoryBuilder_ == null) {
          if (clearHistory_ != null) {
            clearHistory_ =
              com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.newBuilder(clearHistory_).mergeFrom(value).buildPartial();
          } else {
            clearHistory_ = value;
          }
          onChanged();
        } else {
          clearHistoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      public Builder clearClearHistory() {
        if (clearHistoryBuilder_ == null) {
          clearHistory_ = null;
          onChanged();
        } else {
          clearHistory_ = null;
          clearHistoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      public com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.Builder getClearHistoryBuilder() {
        
        onChanged();
        return getClearHistoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      public com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistoryOrBuilder getClearHistoryOrBuilder() {
        if (clearHistoryBuilder_ != null) {
          return clearHistoryBuilder_.getMessageOrBuilder();
        } else {
          return clearHistory_ == null ?
              com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.getDefaultInstance() : clearHistory_;
        }
      }
      /**
       * <code>.msggamedata.MsgDungeonBattleClearHistory clear_history = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory, com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.Builder, com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistoryOrBuilder> 
          getClearHistoryFieldBuilder() {
        if (clearHistoryBuilder_ == null) {
          clearHistoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory, com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistory.Builder, com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.MsgDungeonBattleClearHistoryOrBuilder>(
                  getClearHistory(),
                  getParentForChildren(),
                  isClean());
          clearHistory_ = null;
        }
        return clearHistoryBuilder_;
      }

      private com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook colossusClearReward_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook, com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.Builder, com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBookOrBuilder> colossusClearRewardBuilder_;
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      public boolean hasColossusClearReward() {
        return colossusClearRewardBuilder_ != null || colossusClearReward_ != null;
      }
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      public com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook getColossusClearReward() {
        if (colossusClearRewardBuilder_ == null) {
          return colossusClearReward_ == null ? com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.getDefaultInstance() : colossusClearReward_;
        } else {
          return colossusClearRewardBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      public Builder setColossusClearReward(com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook value) {
        if (colossusClearRewardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          colossusClearReward_ = value;
          onChanged();
        } else {
          colossusClearRewardBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      public Builder setColossusClearReward(
          com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.Builder builderForValue) {
        if (colossusClearRewardBuilder_ == null) {
          colossusClearReward_ = builderForValue.build();
          onChanged();
        } else {
          colossusClearRewardBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      public Builder mergeColossusClearReward(com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook value) {
        if (colossusClearRewardBuilder_ == null) {
          if (colossusClearReward_ != null) {
            colossusClearReward_ =
              com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.newBuilder(colossusClearReward_).mergeFrom(value).buildPartial();
          } else {
            colossusClearReward_ = value;
          }
          onChanged();
        } else {
          colossusClearRewardBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      public Builder clearColossusClearReward() {
        if (colossusClearRewardBuilder_ == null) {
          colossusClearReward_ = null;
          onChanged();
        } else {
          colossusClearReward_ = null;
          colossusClearRewardBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      public com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.Builder getColossusClearRewardBuilder() {
        
        onChanged();
        return getColossusClearRewardFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      public com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBookOrBuilder getColossusClearRewardOrBuilder() {
        if (colossusClearRewardBuilder_ != null) {
          return colossusClearRewardBuilder_.getMessageOrBuilder();
        } else {
          return colossusClearReward_ == null ?
              com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.getDefaultInstance() : colossusClearReward_;
        }
      }
      /**
       * <code>.msggamedata.MsgUserMonsterSkillBook colossus_clear_reward = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook, com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.Builder, com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBookOrBuilder> 
          getColossusClearRewardFieldBuilder() {
        if (colossusClearRewardBuilder_ == null) {
          colossusClearRewardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook, com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBook.Builder, com.felania.msldb.MsgUserMonsterSkillBookOuterClass.MsgUserMonsterSkillBookOrBuilder>(
                  getColossusClearReward(),
                  getParentForChildren(),
                  isClean());
          colossusClearReward_ = null;
        }
        return colossusClearRewardBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msggamedata.MsgRspBattleEndDungeon)
    }

    // @@protoc_insertion_point(class_scope:msggamedata.MsgRspBattleEndDungeon)
    private static final com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon();
    }

    public static com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgRspBattleEndDungeon>
        PARSER = new com.google.protobuf.AbstractParser<MsgRspBattleEndDungeon>() {
      public MsgRspBattleEndDungeon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgRspBattleEndDungeon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgRspBattleEndDungeon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgRspBattleEndDungeon> getParserForType() {
      return PARSER;
    }

    public com.felania.msldb.MsgRspBattleEndDungeonOuterClass.MsgRspBattleEndDungeon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msggamedata_MsgRspBattleEndDungeon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msggamedata_MsgRspBattleEndDungeon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034MsgRspBattleEndDungeon.proto\022\013msggamed" +
      "ata\032\033MsgBattleEndBasicInfo.proto\032 MsgUse" +
      "rDungeonStageHistory.proto\032(MsgUserColos" +
      "susDungeonStageHistory.proto\032\"MsgDungeon" +
      "BattleClearHistory.proto\032\035MsgUserMonster" +
      "SkillBook.proto\"\342\002\n\026MsgRspBattleEndDunge" +
      "on\0220\n\004info\030\001 \001(\0132\".msggamedata.MsgBattle" +
      "EndBasicInfo\022>\n\rstage_history\030\002 \001(\0132\'.ms" +
      "ggamedata.MsgUserDungeonStageHistory\022O\n\026" +
      "colossus_stage_history\030\003 \001(\0132/.msggameda",
      "ta.MsgUserColossusDungeonStageHistory\022@\n" +
      "\rclear_history\030\004 \001(\0132).msggamedata.MsgDu" +
      "ngeonBattleClearHistory\022C\n\025colossus_clea" +
      "r_reward\030\005 \001(\0132$.msggamedata.MsgUserMons" +
      "terSkillBookB\023\n\021com.felania.msldbb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.felania.msldb.MsgBattleEndBasicInfoOuterClass.getDescriptor(),
          com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.getDescriptor(),
          com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.getDescriptor(),
          com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.getDescriptor(),
          com.felania.msldb.MsgUserMonsterSkillBookOuterClass.getDescriptor(),
        }, assigner);
    internal_static_msggamedata_MsgRspBattleEndDungeon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msggamedata_MsgRspBattleEndDungeon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msggamedata_MsgRspBattleEndDungeon_descriptor,
        new java.lang.String[] { "Info", "StageHistory", "ColossusStageHistory", "ClearHistory", "ColossusClearReward", });
    com.felania.msldb.MsgBattleEndBasicInfoOuterClass.getDescriptor();
    com.felania.msldb.MsgUserDungeonStageHistoryOuterClass.getDescriptor();
    com.felania.msldb.MsgUserColossusDungeonStageHistoryOuterClass.getDescriptor();
    com.felania.msldb.MsgDungeonBattleClearHistoryOuterClass.getDescriptor();
    com.felania.msldb.MsgUserMonsterSkillBookOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
