// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgUserShip.proto

package com.felania.msldb;

public final class MsgUserShipOuterClass {
  private MsgUserShipOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgUserShipOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msggamedata.MsgUserShip)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
     */
    int getShipTypeValue();
    /**
     * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
     */
    com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType getShipType();

    /**
     * <code>uint64 expire_date = 3;</code>
     */
    long getExpireDate();

    /**
     * <code>fixed32 shop_item_uid = 4;</code>
     */
    int getShopItemUid();

    /**
     * <code>string name = 5;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 5;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code msggamedata.MsgUserShip}
   */
  public  static final class MsgUserShip extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msggamedata.MsgUserShip)
      MsgUserShipOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgUserShip.newBuilder() to construct.
    private MsgUserShip(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgUserShip() {
      userId_ = 0L;
      shipType_ = 0;
      expireDate_ = 0L;
      shopItemUid_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgUserShip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              shipType_ = rawValue;
              break;
            }
            case 24: {

              expireDate_ = input.readUInt64();
              break;
            }
            case 37: {

              shopItemUid_ = input.readFixed32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.felania.msldb.MsgUserShipOuterClass.internal_static_msggamedata_MsgUserShip_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.felania.msldb.MsgUserShipOuterClass.internal_static_msggamedata_MsgUserShip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.felania.msldb.MsgUserShipOuterClass.MsgUserShip.class, com.felania.msldb.MsgUserShipOuterClass.MsgUserShip.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>uint64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int SHIP_TYPE_FIELD_NUMBER = 2;
    private int shipType_;
    /**
     * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
     */
    public int getShipTypeValue() {
      return shipType_;
    }
    /**
     * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
     */
    public com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType getShipType() {
      com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType result = com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType.valueOf(shipType_);
      return result == null ? com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType.UNRECOGNIZED : result;
    }

    public static final int EXPIRE_DATE_FIELD_NUMBER = 3;
    private long expireDate_;
    /**
     * <code>uint64 expire_date = 3;</code>
     */
    public long getExpireDate() {
      return expireDate_;
    }

    public static final int SHOP_ITEM_UID_FIELD_NUMBER = 4;
    private int shopItemUid_;
    /**
     * <code>fixed32 shop_item_uid = 4;</code>
     */
    public int getShopItemUid() {
      return shopItemUid_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeUInt64(1, userId_);
      }
      if (shipType_ != com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType.SLT_DEFAULT.getNumber()) {
        output.writeEnum(2, shipType_);
      }
      if (expireDate_ != 0L) {
        output.writeUInt64(3, expireDate_);
      }
      if (shopItemUid_ != 0) {
        output.writeFixed32(4, shopItemUid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, userId_);
      }
      if (shipType_ != com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType.SLT_DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, shipType_);
      }
      if (expireDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, expireDate_);
      }
      if (shopItemUid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, shopItemUid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.felania.msldb.MsgUserShipOuterClass.MsgUserShip)) {
        return super.equals(obj);
      }
      com.felania.msldb.MsgUserShipOuterClass.MsgUserShip other = (com.felania.msldb.MsgUserShipOuterClass.MsgUserShip) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && shipType_ == other.shipType_;
      result = result && (getExpireDate()
          == other.getExpireDate());
      result = result && (getShopItemUid()
          == other.getShopItemUid());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + SHIP_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + shipType_;
      hash = (37 * hash) + EXPIRE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpireDate());
      hash = (37 * hash) + SHOP_ITEM_UID_FIELD_NUMBER;
      hash = (53 * hash) + getShopItemUid();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.felania.msldb.MsgUserShipOuterClass.MsgUserShip prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msggamedata.MsgUserShip}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msggamedata.MsgUserShip)
        com.felania.msldb.MsgUserShipOuterClass.MsgUserShipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.felania.msldb.MsgUserShipOuterClass.internal_static_msggamedata_MsgUserShip_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.felania.msldb.MsgUserShipOuterClass.internal_static_msggamedata_MsgUserShip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.felania.msldb.MsgUserShipOuterClass.MsgUserShip.class, com.felania.msldb.MsgUserShipOuterClass.MsgUserShip.Builder.class);
      }

      // Construct using com.felania.msldb.MsgUserShipOuterClass.MsgUserShip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        shipType_ = 0;

        expireDate_ = 0L;

        shopItemUid_ = 0;

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.felania.msldb.MsgUserShipOuterClass.internal_static_msggamedata_MsgUserShip_descriptor;
      }

      public com.felania.msldb.MsgUserShipOuterClass.MsgUserShip getDefaultInstanceForType() {
        return com.felania.msldb.MsgUserShipOuterClass.MsgUserShip.getDefaultInstance();
      }

      public com.felania.msldb.MsgUserShipOuterClass.MsgUserShip build() {
        com.felania.msldb.MsgUserShipOuterClass.MsgUserShip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.felania.msldb.MsgUserShipOuterClass.MsgUserShip buildPartial() {
        com.felania.msldb.MsgUserShipOuterClass.MsgUserShip result = new com.felania.msldb.MsgUserShipOuterClass.MsgUserShip(this);
        result.userId_ = userId_;
        result.shipType_ = shipType_;
        result.expireDate_ = expireDate_;
        result.shopItemUid_ = shopItemUid_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.felania.msldb.MsgUserShipOuterClass.MsgUserShip) {
          return mergeFrom((com.felania.msldb.MsgUserShipOuterClass.MsgUserShip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.felania.msldb.MsgUserShipOuterClass.MsgUserShip other) {
        if (other == com.felania.msldb.MsgUserShipOuterClass.MsgUserShip.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.shipType_ != 0) {
          setShipTypeValue(other.getShipTypeValue());
        }
        if (other.getExpireDate() != 0L) {
          setExpireDate(other.getExpireDate());
        }
        if (other.getShopItemUid() != 0) {
          setShopItemUid(other.getShopItemUid());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.felania.msldb.MsgUserShipOuterClass.MsgUserShip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.felania.msldb.MsgUserShipOuterClass.MsgUserShip) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>uint64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>uint64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private int shipType_ = 0;
      /**
       * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
       */
      public int getShipTypeValue() {
        return shipType_;
      }
      /**
       * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
       */
      public Builder setShipTypeValue(int value) {
        shipType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
       */
      public com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType getShipType() {
        com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType result = com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType.valueOf(shipType_);
        return result == null ? com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType.UNRECOGNIZED : result;
      }
      /**
       * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
       */
      public Builder setShipType(com.felania.msldb.ShipLobbyTypeOuterClass.ShipLobbyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        shipType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.msggamedata.ShipLobbyType ship_type = 2;</code>
       */
      public Builder clearShipType() {
        
        shipType_ = 0;
        onChanged();
        return this;
      }

      private long expireDate_ ;
      /**
       * <code>uint64 expire_date = 3;</code>
       */
      public long getExpireDate() {
        return expireDate_;
      }
      /**
       * <code>uint64 expire_date = 3;</code>
       */
      public Builder setExpireDate(long value) {
        
        expireDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 expire_date = 3;</code>
       */
      public Builder clearExpireDate() {
        
        expireDate_ = 0L;
        onChanged();
        return this;
      }

      private int shopItemUid_ ;
      /**
       * <code>fixed32 shop_item_uid = 4;</code>
       */
      public int getShopItemUid() {
        return shopItemUid_;
      }
      /**
       * <code>fixed32 shop_item_uid = 4;</code>
       */
      public Builder setShopItemUid(int value) {
        
        shopItemUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 shop_item_uid = 4;</code>
       */
      public Builder clearShopItemUid() {
        
        shopItemUid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 5;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msggamedata.MsgUserShip)
    }

    // @@protoc_insertion_point(class_scope:msggamedata.MsgUserShip)
    private static final com.felania.msldb.MsgUserShipOuterClass.MsgUserShip DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.felania.msldb.MsgUserShipOuterClass.MsgUserShip();
    }

    public static com.felania.msldb.MsgUserShipOuterClass.MsgUserShip getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgUserShip>
        PARSER = new com.google.protobuf.AbstractParser<MsgUserShip>() {
      public MsgUserShip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgUserShip(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgUserShip> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgUserShip> getParserForType() {
      return PARSER;
    }

    public com.felania.msldb.MsgUserShipOuterClass.MsgUserShip getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msggamedata_MsgUserShip_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msggamedata_MsgUserShip_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MsgUserShip.proto\022\013msggamedata\032\023ShipLo" +
      "bbyType.proto\"\207\001\n\013MsgUserShip\022\017\n\007user_id" +
      "\030\001 \001(\004\022-\n\tship_type\030\002 \001(\0162\032.msggamedata." +
      "ShipLobbyType\022\023\n\013expire_date\030\003 \001(\004\022\025\n\rsh" +
      "op_item_uid\030\004 \001(\007\022\014\n\004name\030\005 \001(\tB\023\n\021com.f" +
      "elania.msldbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.felania.msldb.ShipLobbyTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_msggamedata_MsgUserShip_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msggamedata_MsgUserShip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msggamedata_MsgUserShip_descriptor,
        new java.lang.String[] { "UserId", "ShipType", "ExpireDate", "ShopItemUid", "Name", });
    com.felania.msldb.ShipLobbyTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
