// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReqUserBingoEventReward.proto

package com.felania.msldb;

public final class ReqUserBingoEventRewardOuterClass {
  private ReqUserBingoEventRewardOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqUserBingoEventRewardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msggamedata.ReqUserBingoEventReward)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 rewardable_idx = 1;</code>
     */
    int getRewardableIdx();
  }
  /**
   * Protobuf type {@code msggamedata.ReqUserBingoEventReward}
   */
  public  static final class ReqUserBingoEventReward extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msggamedata.ReqUserBingoEventReward)
      ReqUserBingoEventRewardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqUserBingoEventReward.newBuilder() to construct.
    private ReqUserBingoEventReward(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqUserBingoEventReward() {
      rewardableIdx_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqUserBingoEventReward(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              rewardableIdx_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.felania.msldb.ReqUserBingoEventRewardOuterClass.internal_static_msggamedata_ReqUserBingoEventReward_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.felania.msldb.ReqUserBingoEventRewardOuterClass.internal_static_msggamedata_ReqUserBingoEventReward_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward.class, com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward.Builder.class);
    }

    public static final int REWARDABLE_IDX_FIELD_NUMBER = 1;
    private int rewardableIdx_;
    /**
     * <code>uint32 rewardable_idx = 1;</code>
     */
    public int getRewardableIdx() {
      return rewardableIdx_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rewardableIdx_ != 0) {
        output.writeUInt32(1, rewardableIdx_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rewardableIdx_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, rewardableIdx_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward)) {
        return super.equals(obj);
      }
      com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward other = (com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward) obj;

      boolean result = true;
      result = result && (getRewardableIdx()
          == other.getRewardableIdx());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REWARDABLE_IDX_FIELD_NUMBER;
      hash = (53 * hash) + getRewardableIdx();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msggamedata.ReqUserBingoEventReward}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msggamedata.ReqUserBingoEventReward)
        com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventRewardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.felania.msldb.ReqUserBingoEventRewardOuterClass.internal_static_msggamedata_ReqUserBingoEventReward_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.felania.msldb.ReqUserBingoEventRewardOuterClass.internal_static_msggamedata_ReqUserBingoEventReward_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward.class, com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward.Builder.class);
      }

      // Construct using com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rewardableIdx_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.felania.msldb.ReqUserBingoEventRewardOuterClass.internal_static_msggamedata_ReqUserBingoEventReward_descriptor;
      }

      public com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward getDefaultInstanceForType() {
        return com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward.getDefaultInstance();
      }

      public com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward build() {
        com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward buildPartial() {
        com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward result = new com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward(this);
        result.rewardableIdx_ = rewardableIdx_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward) {
          return mergeFrom((com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward other) {
        if (other == com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward.getDefaultInstance()) return this;
        if (other.getRewardableIdx() != 0) {
          setRewardableIdx(other.getRewardableIdx());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int rewardableIdx_ ;
      /**
       * <code>uint32 rewardable_idx = 1;</code>
       */
      public int getRewardableIdx() {
        return rewardableIdx_;
      }
      /**
       * <code>uint32 rewardable_idx = 1;</code>
       */
      public Builder setRewardableIdx(int value) {
        
        rewardableIdx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 rewardable_idx = 1;</code>
       */
      public Builder clearRewardableIdx() {
        
        rewardableIdx_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msggamedata.ReqUserBingoEventReward)
    }

    // @@protoc_insertion_point(class_scope:msggamedata.ReqUserBingoEventReward)
    private static final com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward();
    }

    public static com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqUserBingoEventReward>
        PARSER = new com.google.protobuf.AbstractParser<ReqUserBingoEventReward>() {
      public ReqUserBingoEventReward parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqUserBingoEventReward(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqUserBingoEventReward> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqUserBingoEventReward> getParserForType() {
      return PARSER;
    }

    public com.felania.msldb.ReqUserBingoEventRewardOuterClass.ReqUserBingoEventReward getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msggamedata_ReqUserBingoEventReward_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msggamedata_ReqUserBingoEventReward_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ReqUserBingoEventReward.proto\022\013msggame" +
      "data\"1\n\027ReqUserBingoEventReward\022\026\n\016rewar" +
      "dable_idx\030\001 \001(\rB\023\n\021com.felania.msldbb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_msggamedata_ReqUserBingoEventReward_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msggamedata_ReqUserBingoEventReward_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msggamedata_ReqUserBingoEventReward_descriptor,
        new java.lang.String[] { "RewardableIdx", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
