// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RspReceiveAllUserGift.proto

package com.felania.msldb;

public final class RspReceiveAllUserGiftOuterClass {
  private RspReceiveAllUserGiftOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RspReceiveAllUserGiftOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msggamedata.RspReceiveAllUserGift)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint64 gift_ids = 1;</code>
     */
    java.util.List<java.lang.Long> getGiftIdsList();
    /**
     * <code>repeated uint64 gift_ids = 1;</code>
     */
    int getGiftIdsCount();
    /**
     * <code>repeated uint64 gift_ids = 1;</code>
     */
    long getGiftIds(int index);

    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    boolean hasUser();
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    com.felania.msldb.MsgUserOuterClass.MsgUser getUser();
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder getUserOrBuilder();

    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    java.util.List<com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem> 
        getItemsList();
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem getItems(int index);
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    java.util.List<? extends com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code msggamedata.RspReceiveAllUserGift}
   */
  public  static final class RspReceiveAllUserGift extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msggamedata.RspReceiveAllUserGift)
      RspReceiveAllUserGiftOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RspReceiveAllUserGift.newBuilder() to construct.
    private RspReceiveAllUserGift(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RspReceiveAllUserGift() {
      giftIds_ = java.util.Collections.emptyList();
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RspReceiveAllUserGift(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                giftIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              giftIds_.add(input.readUInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                giftIds_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                giftIds_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              com.felania.msldb.MsgUserOuterClass.MsgUser.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(com.felania.msldb.MsgUserOuterClass.MsgUser.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                items_ = new java.util.ArrayList<com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem>();
                mutable_bitField0_ |= 0x00000004;
              }
              items_.add(
                  input.readMessage(com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          giftIds_ = java.util.Collections.unmodifiableList(giftIds_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.felania.msldb.RspReceiveAllUserGiftOuterClass.internal_static_msggamedata_RspReceiveAllUserGift_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.felania.msldb.RspReceiveAllUserGiftOuterClass.internal_static_msggamedata_RspReceiveAllUserGift_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift.class, com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift.Builder.class);
    }

    private int bitField0_;
    public static final int GIFT_IDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> giftIds_;
    /**
     * <code>repeated uint64 gift_ids = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getGiftIdsList() {
      return giftIds_;
    }
    /**
     * <code>repeated uint64 gift_ids = 1;</code>
     */
    public int getGiftIdsCount() {
      return giftIds_.size();
    }
    /**
     * <code>repeated uint64 gift_ids = 1;</code>
     */
    public long getGiftIds(int index) {
      return giftIds_.get(index);
    }
    private int giftIdsMemoizedSerializedSize = -1;

    public static final int USER_FIELD_NUMBER = 2;
    private com.felania.msldb.MsgUserOuterClass.MsgUser user_;
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    public com.felania.msldb.MsgUserOuterClass.MsgUser getUser() {
      return user_ == null ? com.felania.msldb.MsgUserOuterClass.MsgUser.getDefaultInstance() : user_;
    }
    /**
     * <code>.msggamedata.MsgUser user = 2;</code>
     */
    public com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int ITEMS_FIELD_NUMBER = 3;
    private java.util.List<com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem> items_;
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    public java.util.List<com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    public java.util.List<? extends com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    public com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
     */
    public com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getGiftIdsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(giftIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < giftIds_.size(); i++) {
        output.writeUInt64NoTag(giftIds_.get(i));
      }
      if (user_ != null) {
        output.writeMessage(2, getUser());
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(3, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < giftIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(giftIds_.get(i));
        }
        size += dataSize;
        if (!getGiftIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        giftIdsMemoizedSerializedSize = dataSize;
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUser());
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift)) {
        return super.equals(obj);
      }
      com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift other = (com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift) obj;

      boolean result = true;
      result = result && getGiftIdsList()
          .equals(other.getGiftIdsList());
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && getItemsList()
          .equals(other.getItemsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGiftIdsCount() > 0) {
        hash = (37 * hash) + GIFT_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getGiftIdsList().hashCode();
      }
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msggamedata.RspReceiveAllUserGift}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msggamedata.RspReceiveAllUserGift)
        com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGiftOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.felania.msldb.RspReceiveAllUserGiftOuterClass.internal_static_msggamedata_RspReceiveAllUserGift_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.felania.msldb.RspReceiveAllUserGiftOuterClass.internal_static_msggamedata_RspReceiveAllUserGift_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift.class, com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift.Builder.class);
      }

      // Construct using com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        giftIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.felania.msldb.RspReceiveAllUserGiftOuterClass.internal_static_msggamedata_RspReceiveAllUserGift_descriptor;
      }

      public com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift getDefaultInstanceForType() {
        return com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift.getDefaultInstance();
      }

      public com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift build() {
        com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift buildPartial() {
        com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift result = new com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          giftIds_ = java.util.Collections.unmodifiableList(giftIds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.giftIds_ = giftIds_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift) {
          return mergeFrom((com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift other) {
        if (other == com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift.getDefaultInstance()) return this;
        if (!other.giftIds_.isEmpty()) {
          if (giftIds_.isEmpty()) {
            giftIds_ = other.giftIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGiftIdsIsMutable();
            giftIds_.addAll(other.giftIds_);
          }
          onChanged();
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000004);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> giftIds_ = java.util.Collections.emptyList();
      private void ensureGiftIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          giftIds_ = new java.util.ArrayList<java.lang.Long>(giftIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint64 gift_ids = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getGiftIdsList() {
        return java.util.Collections.unmodifiableList(giftIds_);
      }
      /**
       * <code>repeated uint64 gift_ids = 1;</code>
       */
      public int getGiftIdsCount() {
        return giftIds_.size();
      }
      /**
       * <code>repeated uint64 gift_ids = 1;</code>
       */
      public long getGiftIds(int index) {
        return giftIds_.get(index);
      }
      /**
       * <code>repeated uint64 gift_ids = 1;</code>
       */
      public Builder setGiftIds(
          int index, long value) {
        ensureGiftIdsIsMutable();
        giftIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 gift_ids = 1;</code>
       */
      public Builder addGiftIds(long value) {
        ensureGiftIdsIsMutable();
        giftIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 gift_ids = 1;</code>
       */
      public Builder addAllGiftIds(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureGiftIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, giftIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 gift_ids = 1;</code>
       */
      public Builder clearGiftIds() {
        giftIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.felania.msldb.MsgUserOuterClass.MsgUser user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserOuterClass.MsgUser, com.felania.msldb.MsgUserOuterClass.MsgUser.Builder, com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder> userBuilder_;
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public com.felania.msldb.MsgUserOuterClass.MsgUser getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? com.felania.msldb.MsgUserOuterClass.MsgUser.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public Builder setUser(com.felania.msldb.MsgUserOuterClass.MsgUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public Builder setUser(
          com.felania.msldb.MsgUserOuterClass.MsgUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public Builder mergeUser(com.felania.msldb.MsgUserOuterClass.MsgUser value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              com.felania.msldb.MsgUserOuterClass.MsgUser.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public com.felania.msldb.MsgUserOuterClass.MsgUser.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      public com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              com.felania.msldb.MsgUserOuterClass.MsgUser.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.msggamedata.MsgUser user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.felania.msldb.MsgUserOuterClass.MsgUser, com.felania.msldb.MsgUserOuterClass.MsgUser.Builder, com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.felania.msldb.MsgUserOuterClass.MsgUser, com.felania.msldb.MsgUserOuterClass.MsgUser.Builder, com.felania.msldb.MsgUserOuterClass.MsgUserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private java.util.List<com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          items_ = new java.util.ArrayList<com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem>(items_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public java.util.List<com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder setItems(
          int index, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder setItems(
          int index, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder addItems(com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder addItems(
          int index, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder addItems(
          com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder addItems(
          int index, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public java.util.List<? extends com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.getDefaultInstance());
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.getDefaultInstance());
      }
      /**
       * <code>repeated .msggamedata.MsgGiftItem items = 3;</code>
       */
      public java.util.List<com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItem.Builder, com.felania.msldb.MsgGiftItemOuterClass.MsgGiftItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msggamedata.RspReceiveAllUserGift)
    }

    // @@protoc_insertion_point(class_scope:msggamedata.RspReceiveAllUserGift)
    private static final com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift();
    }

    public static com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RspReceiveAllUserGift>
        PARSER = new com.google.protobuf.AbstractParser<RspReceiveAllUserGift>() {
      public RspReceiveAllUserGift parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RspReceiveAllUserGift(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RspReceiveAllUserGift> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RspReceiveAllUserGift> getParserForType() {
      return PARSER;
    }

    public com.felania.msldb.RspReceiveAllUserGiftOuterClass.RspReceiveAllUserGift getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msggamedata_RspReceiveAllUserGift_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msggamedata_RspReceiveAllUserGift_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033RspReceiveAllUserGift.proto\022\013msggameda" +
      "ta\032\rMsgUser.proto\032\021MsgGiftItem.proto\"v\n\025" +
      "RspReceiveAllUserGift\022\020\n\010gift_ids\030\001 \003(\004\022" +
      "\"\n\004user\030\002 \001(\0132\024.msggamedata.MsgUser\022\'\n\005i" +
      "tems\030\003 \003(\0132\030.msggamedata.MsgGiftItemB\023\n\021" +
      "com.felania.msldbb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.felania.msldb.MsgUserOuterClass.getDescriptor(),
          com.felania.msldb.MsgGiftItemOuterClass.getDescriptor(),
        }, assigner);
    internal_static_msggamedata_RspReceiveAllUserGift_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msggamedata_RspReceiveAllUserGift_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msggamedata_RspReceiveAllUserGift_descriptor,
        new java.lang.String[] { "GiftIds", "User", "Items", });
    com.felania.msldb.MsgUserOuterClass.getDescriptor();
    com.felania.msldb.MsgGiftItemOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
